import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Hamburger from "@/components/ui/Hamburger";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-screen">
          <div className="w-full bg-[#9b6484] text-white font-semibold">
            <div
              className="flex flex-col md:flex-row justify-between items-center
            w-[min(1250px,95vw)]
            m-auto"
            >
              <div>Number</div>
              <div className="hidden md:block">Info</div>
              <div>Idioma/Location</div>
            </div>
          </div>
          <div className=" border-b-2 border-gray-100 flex items-center justify-between w-[min(1250px,95vw)] m-auto py-2">
            <div className="lg:hidden">
              <Hamburger />
            </div>
            <a className="hidden lg:block order-1 sm:order-0" href="/">
              <div className="w-[50px] h-[50px] rounded-[50px] bg-red-100"></div>
            </a>
            <div className="hidden lg:flex lg:justify-center lg:gap-10 order-2">
              <a href="/products">Categorias</a>
              <a href="/products">Producos</a>
            </div>
            <div className="hidden lg:block order-3">
              <input
                className="rounded-[20px] px-4 border-2 border-gray-200 focus:outline-none"
                type="text"
                placeholder="buscar"
              />
            </div>
            <div className="flex flex-row order-4 gap-2 sm:flex-row sm:gap-8">
              <a href="/auth" className="flex">
                {/* <Image src="/icons/login.png" alt="" /> */}
                <span>Cuenta</span>
              </a>
              <a href="/cart" className="flex items-center">
                {/* <img src="/icons/cart.png" alt="" /> */}
                <span>Carrito</span>
              </a>
            </div>
          </div>
        </header>

        {children}
        <footer
          className="w-[min(1250px,95vw)] m-auto
        border-2 border-blue-100"
        >
          <section className="footer-items">
            <article
              className="company
            border-2 border-red-100"
            >
              Empresa
            </article>
            <article className="payment border-2 border-red-200">
              Pagos aceptados
            </article>
            <article className="department border-2 border-red-200">
              Departamentos
            </article>
            <article className="about-us border-2 border-red-200">
              Sobre Nosotros
            </article>
            <article className="services border-2 border-red-200">
              Servicios
            </article>
            <article className="help border-2 border-red-200">Ayuda</article>
          </section>
          <section className="flex flex-wrap justify-between flex-col sm:flex-row">
            <div className="flex flex-wrap justify-between">
              <p className="mx-2">Vende tú</p>
              <p className="mx-2">Gitf Cards</p>
              <p className="mx-2">Help center</p>
            </div>
            <div className="flex flex-wrap justify-between">
              <p>Terminos de servicio</p>
              <p>Privacidad</p>
            </div>
            <div className="flex flex-wrap justify-center">
              <p>dlwldma@2023</p>
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
